### ISSUE TITLE
http_request with Segmentation fault

### ISSUE THREAD

**Issue by lxlenovostar** [creytiv/re#123]
The same codes can run on Ubuntu(x86_64) and openwrt(ARM), but it can't run on CentOS6.8(x86_64).

Segmentation fault happen on:
```
Program received signal SIGSEGV, Segmentation fault.
fd_handler (re=Cannot access memory at address 0xffffffffffffffe8
) at src/main/main.c:242
242	G_WARNING("1 event on fd=%d (flags=0x%02x)...\n", fd, flags);


```
```
static void fd_handler(struct re *re, int fd, int flags)
{
        const uint64_t tick = tmr_jiffies();
        uint32_t diff;

        DEBUG_INFO("event on fd=%d (flags=0x%02x)...\n", fd, flags);

        DEBUG_WARNING("0 event on fd=%d (flags=0x%02x)...\n", fd, flags);
        re->fhs[fd].fh(flags, re->fhs[fd].arg);
        DEBUG_WARNING("1 event on fd=%d (flags=0x%02x)...\n", fd, flags);

        diff = (uint32_t)(tmr_jiffies() - tick);

        if (diff > MAX_BLOCKING) {
                DEBUG_WARNING("long async blocking: %u>%u ms (h=%p arg=%p)\n",
                              diff, MAX_BLOCKING,
                              re->fhs[fd].fh, re->fhs[fd].arg);
        }
}

```

Before Segmentation fault, the call stack is:
```
Breakpoint 1, http_resp_handler_get_flv_file (err=0, msg=0x674660, arg=0x66c890) at /root/lix/rawrtc-terminal-demo/c/src/rawrtc-terminal.c:314
314	    struct http_arg* h_arg = (struct http_arg*)arg;
(gdb) bt
#0  http_resp_handler_get_flv_file (err=0, msg=0x674660, arg=0x66c890) at /root/lix/rawrtc-terminal-demo/c/src/rawrtc-terminal.c:314
#1  0x000000000040fe7c in req_close (req=0x6782e0, err=0, msg=0x674660) at src/http/client.c:165
#2  0x0000000000410564 in recv_handler (mb=0x676cc0, arg=0x6730b0) at src/http/client.c:373
#3  0x000000000041a4bb in tcp_recv_handler (flags=1, arg=0x673260) at src/tcp/tcp.c:434
#4  0x0000000000423b9e in fd_handler (re=Cannot access memory at address 0xffffffffffffffe8
) at src/main/main.c:241
```

The codes is:
```
//TODO not use malloc
        struct http_arg *arg = (struct http_arg*)malloc(sizeof(struct http_arg));             
        arg->flvname = agent->latest_time;                                                    
        arg->agent = agent;
        
        //TODO need check
        http_client_get(agent->flv_http_client, flv_buf, http_resp_handler_get_flv_file, arg);


```

```
/*
 * success return 0, or return -1.
 * */
static int http_client_get(struct http_cli * const cli, const char* url, http_resp_h *h_resph, void *arg)
{
        //struct http_cli *cli = agent->conf_http_client;
        struct http_req *req = NULL;
        int err = 0;

        err = http_request(&req, cli, "GET", url, h_resph, NULL, arg, NULL);
        if (err) {
                DEBUG_WARNING("http_request fail, errno:%d, url:%s\n", err, url);
                return -1;
        }

        return 0;
}

```
```
static void http_resp_handler_get_flv_file(int err, const struct http_msg *msg, void *arg)
{
    struct http_arg* h_arg = (struct http_arg*)arg;
    struct peer_group* const agent = h_arg->agent;
    int flvname = h_arg->flvname;

        // TODO: http timeout. CONN_TIMEOUT = 30000
        if (err) {
                DEBUG_WARNING("get flv file fail. %d\n", err);
                free(h_arg);
                return;
        }

```

This is why? And how to debug it?
Thank you.

**Comment by lxlenovostar** [comment]
I recompile libre on CentOS, and it work.
